---
- name: Install Grafana
  yum: 
    name: "{{item}}" 
    state: installed
  with_items: "{{grafana_packages}}"
  tags: package

- name: Confirure Grafana
  template: 
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify: restart grafana

- name: Install Grafana service
  service: 
    name: grafana-server 
    state: started
    enabled: yes

- name: Configure default dashboard
  uri:
    HEADER_Content-Type: application/json
    url: http://localhost:3000/api/dashboards/db
    method: POST
    user: admin
    password: password
    body: "{{ lookup('file',grafana_custom_dashboard) }}"
    force_basic_auth: yes
  tags: dashboard
  register: result
  failed_when: result.status != 200 and result.status != 412
  when: grafana_custom_dashboard
